export const ROOT_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const USER_ROUTE = '/user'
export const LOGIN_ROUTE = '/login'
export const COMPANY_ROUTE = '/company'
export const COMPANY_EDIT_ROUTE = '/company/:id'
export const USER_EDIT_ROUTE = '/user/:id'
export const REGISTRATION_ROUTE = '/registration'
